export const qk = {
  forecasts: (horizon: string, universe: string[], themes?: string[]) => [
    'forecasts',
    horizon,
    [...universe].sort().join(','),
    (themes ?? []).sort().join(','),
  ],
  macroSeries: (ids: string[]) => ['macro-series', [...ids].sort().join(',')],
  news: (universe: string[], limit: number) => ['news', [...universe].sort().join(','), limit],
  performanceMatrix: (
    horizons: string[],
    tickers: string[],
    sectors: string[],
    themes: string[],
  ) => [
    'performance-matrix',
    [...horizons].sort().join(','),
    [...tickers].sort().join(','),
    [...sectors].sort().join(','),
    [...themes].sort().join(','),
  ],
  forecastMatrix: (universe: string[], horizons: string[]) => [
    'forecast-matrix',
    [...universe].sort().join(','),
    [...horizons].sort().join(','),
  ],
  newsRadar: (
    universe: string[],
    themes: string[],
    q: string,
    from: string,
    to: string,
    limit: string | number,
    sort: string,
  ) => [
    'news-radar',
    [...universe].sort().join(','),
    [...themes].sort().join(','),
    q,
    from,
    to,
    String(limit ?? ''),
    sort,
  ],
  search: (type: string, ...params: any[]) => ['search', type, ...params],
  portfolios: () => ['portfolios'],
  portfolio: (id: string) => ['portfolios', id],
  portfolioPerformance: (id: string, benchmark?: string) => ['portfolios', id, 'performance', benchmark ?? 'SPY'],
} as const;
