#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd -P)"

export FC_SCRUM_MASTER_ENABLED="${FC_SCRUM_MASTER_ENABLED:-1}"
export FC_SCRUM_MASTER_MODE="${FC_SCRUM_MASTER_MODE:-operational}"
export FC_SCRUM_MASTER_FULL_REMEDIATION="${FC_SCRUM_MASTER_FULL_REMEDIATION:-1}"
export FC_SCRUM_MASTER_ESCALATE_AFTER_CYCLES="${FC_SCRUM_MASTER_ESCALATE_AFTER_CYCLES:-2}"
export FC_SCRUM_MASTER_ALLOW_BUS_POST="${FC_SCRUM_MASTER_ALLOW_BUS_POST:-1}"
export FC_SCRUM_MASTER_MAX_POSTS_PER_TICK="${FC_SCRUM_MASTER_MAX_POSTS_PER_TICK:-2}"
export FC_SCRUM_MASTER_POST_COOLDOWN_S="${FC_SCRUM_MASTER_POST_COOLDOWN_S:-600}"
export FC_FORCE_ALLOW_FILE_EDITS_ALL="${FC_FORCE_ALLOW_FILE_EDITS_ALL:-1}"
export TMUX_ROLE_ENABLE_SCRUM_MASTER="${TMUX_ROLE_ENABLE_SCRUM_MASTER:-1}"
export TMUX_ROLE_ENABLE_PO_SCRUM_MASTER="${TMUX_ROLE_ENABLE_PO_SCRUM_MASTER:-${TMUX_ROLE_ENABLE_SCRUM_MASTER}}"
export ROLE_ALLOW_FILE_EDITS="${ROLE_ALLOW_FILE_EDITS:-1}"
export FC_SCRUM_MASTER_CRON_ENABLED="${FC_SCRUM_MASTER_CRON_ENABLED:-1}"

exec bash "$ROOT/scripts/fc_agent_tick.sh" scrum_master
