#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd -P)"

# Consolidate admin runtime defaults in one place to keep crontab lines short.
export FC_ADMIN_PROMPT_TIMEOUT_SECONDS="${FC_ADMIN_PROMPT_TIMEOUT_SECONDS:-360}"
export FC_ADMIN_RETRY_TIMEOUT_SECONDS="${FC_ADMIN_RETRY_TIMEOUT_SECONDS:-150}"
export FC_ADMIN_TICK_TIMEOUT_SECONDS="${FC_ADMIN_TICK_TIMEOUT_SECONDS:-540}"
export FC_ADMIN_DISPATCH_ENABLED="${FC_ADMIN_DISPATCH_ENABLED:-1}"
export FC_ADMIN_DISPATCH_COOLDOWN_SECONDS="${FC_ADMIN_DISPATCH_COOLDOWN_SECONDS:-180}"
export FC_ADMIN_DISPATCH_MAX_ACTIONS="${FC_ADMIN_DISPATCH_MAX_ACTIONS:-2}"
export FC_ADMIN_DISPATCH_SYNC_PRIORITY="${FC_ADMIN_DISPATCH_SYNC_PRIORITY:-1}"
export FC_ADMIN_DISPATCH_BYPASS_COOLDOWN_ON_HANDOFF="${FC_ADMIN_DISPATCH_BYPASS_COOLDOWN_ON_HANDOFF:-1}"
export FC_ADMIN_TSHAPE_ENABLED="${FC_ADMIN_TSHAPE_ENABLED:-1}"
export FC_ADMIN_TSHAPE_TRIGGER="${FC_ADMIN_TSHAPE_TRIGGER:-blocked}"
export FC_ADMIN_TSHAPE_BLOCKED_THRESHOLD="${FC_ADMIN_TSHAPE_BLOCKED_THRESHOLD:-1}"
export FC_ADMIN_TSHAPE_SCOPE="${FC_ADMIN_TSHAPE_SCOPE:-full_takeover}"
export FC_ADMIN_TSHAPE_EXIT_POLICY="${FC_ADMIN_TSHAPE_EXIT_POLICY:-resolved_only}"
export FC_ADMIN_TSHAPE_ALLOWED_TARGETS="${FC_ADMIN_TSHAPE_ALLOWED_TARGETS:-planner,dev}"
export FC_ADMIN_TSHAPE_SYNC_TIMEOUT_SECONDS="${FC_ADMIN_TSHAPE_SYNC_TIMEOUT_SECONDS:-20}"
export FC_ADMIN_TSHAPE_ENFORCE_SLA="${FC_ADMIN_TSHAPE_ENFORCE_SLA:-1}"
export FC_ADMIN_TSHAPE_SLA_TIMEOUT_SECONDS="${FC_ADMIN_TSHAPE_SLA_TIMEOUT_SECONDS:-15}"
export FC_ADMIN_TSHAPE_COOLDOWN_SECONDS="${FC_ADMIN_TSHAPE_COOLDOWN_SECONDS:-0}"

exec bash "$ROOT/scripts/fc_agent_tick.sh" admin
