#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd -P)"

export FC_ENABLE_PO_SCRUM_MASTER="${FC_ENABLE_PO_SCRUM_MASTER:-1}"
export FC_PO_SCRUM_MASTER_CRON="${FC_PO_SCRUM_MASTER_CRON:-1}"
export FC_PO_SCRUM_MASTER_RUN_NOW="${FC_PO_SCRUM_MASTER_RUN_NOW:-1}"
export FC_SCRUM_MASTER_MODE="${FC_SCRUM_MASTER_MODE:-operational}"
export FC_SCRUM_MASTER_FULL_REMEDIATION="${FC_SCRUM_MASTER_FULL_REMEDIATION:-1}"
export FC_SCRUM_MASTER_ESCALATE_AFTER_CYCLES="${FC_SCRUM_MASTER_ESCALATE_AFTER_CYCLES:-2}"
export TMUX_ROLE_ENABLE_PO_SCRUM_MASTER="${TMUX_ROLE_ENABLE_PO_SCRUM_MASTER:-1}"
export ROLE_ALLOW_FILE_EDITS="${ROLE_ALLOW_FILE_EDITS:-0}"
export FC_SCRUM_MASTER_CRON_ENABLED="${FC_SCRUM_MASTER_CRON_ENABLED:-1}"

exec bash "$ROOT/scripts/fc_agent_tick.sh" scrum_master
