#!/usr/bin/env bash
# =============================================================================
# lm_used_model_config.sh — SOURCE UNIQUE config modèles LLM
#
# POUR CHANGER UN MODÈLE → modifier un TIER (section 1) ou un rôle (section 2)
# Les scripts ne lisent QUE ce fichier — aucun modèle hardcodé ailleurs.
#
# TIERS:
#   ORCHESTRATION  planner, admin          gpt-5.2 + high   (fiabilité dispatch)
#   BUILD          dev                     gpt-5.3-codex-spark + high  (~40% moins cher)
#   ANALYSIS       data_analyst, integrator gpt-5.3-codex-spark + medium (read-only)
#   VALIDATION     tester, qa              qwen (agent primaire, zéro quota codex)
#   DEEP_DEBUG     override ponctuel       gpt-5.3-codex + high
#
# MODÈLES valides : gpt-5.2 | gpt-5.3-codex-spark | gpt-5.3-codex | qwen
# THINKING valides: minimal | low | medium | high | "" (= défaut config codex)
# FALLBACK chain  : codex rate-limited → qwen → skip
# =============================================================================

set -euo pipefail

# =============================================================================
# SECTION 1 — TIERS  (modifier ici = tous les rôles du tier changent)
# =============================================================================

# ORCHESTRATION — planner premium seulement
LM_TIER_ORCHESTRATION_MODEL="${LM_TIER_ORCHESTRATION_MODEL:-gpt-5.4}"
LM_TIER_ORCHESTRATION_THINKING="${LM_TIER_ORCHESTRATION_THINKING:-xhigh}"

# BUILD — génération code, ops et livraison secondaire — spark
LM_TIER_BUILD_MODEL="${LM_TIER_BUILD_MODEL:-gpt-5.3-codex-spark}"
LM_TIER_BUILD_THINKING="${LM_TIER_BUILD_THINKING:-medium}"

# ANALYSIS — lecture seule, métriques — medium suffit
LM_TIER_ANALYSIS_MODEL="${LM_TIER_ANALYSIS_MODEL:-gpt-5.3-codex-spark}"
LM_TIER_ANALYSIS_THINKING="${LM_TIER_ANALYSIS_THINKING:-high}"

# VALIDATION — tests, docs, QA — qwen natif, zéro quota codex
LM_TIER_VALIDATION_MODEL="${LM_TIER_VALIDATION_MODEL:-qwen}"
LM_TIER_VALIDATION_THINKING="${LM_TIER_VALIDATION_THINKING:-}"

# DEEP_DEBUG — debug profond incidents (override ponctuel)
# Usage: export LM_ROLE_DEV_MODEL="$LM_TIER_DEEP_DEBUG_MODEL"
LM_TIER_DEEP_DEBUG_MODEL="${LM_TIER_DEEP_DEBUG_MODEL:-gpt-5.3-codex}"
LM_TIER_DEEP_DEBUG_THINKING="${LM_TIER_DEEP_DEBUG_THINKING:-high}"

# =============================================================================
# SECTION 2 — PER-ROLE  (3 rôles lean actifs + legacy aliasés)
# =============================================================================

# --- RÔLES LEAN ACTIFS ---
# planner: dispatch batches, mentor vision, coordination → fiabilité max
LM_ROLE_PLANNER_MODEL="${LM_ROLE_PLANNER_MODEL:-${LM_TIER_ORCHESTRATION_MODEL}}"
LM_ROLE_PLANNER_THINKING="${LM_ROLE_PLANNER_THINKING:-${LM_TIER_ORCHESTRATION_THINKING}}"

# dev: code + tests + QA consolidé → spark high
LM_ROLE_DEV_MODEL="${LM_ROLE_DEV_MODEL:-${LM_TIER_BUILD_MODEL}}"
LM_ROLE_DEV_THINKING="${LM_ROLE_DEV_THINKING:-${LM_TIER_BUILD_THINKING}}"

# admin: santé système, déblocage, ops → spark par défaut, fallback qwen si quota
LM_ROLE_ADMIN_MODEL="${LM_ROLE_ADMIN_MODEL:-${LM_TIER_BUILD_MODEL}}"
LM_ROLE_ADMIN_THINKING="${LM_ROLE_ADMIN_THINKING:-${LM_TIER_BUILD_THINKING}}"

# --- RÔLES LEGACY (aliasés vers lean par fc_agent_tick.sh) ---
# Ces vars sont lues si un ancien script invoque encore l'ancien nom
LM_ROLE_BACKEND_ENGINEER_MODEL="${LM_ROLE_BACKEND_ENGINEER_MODEL:-${LM_TIER_BUILD_MODEL}}"
LM_ROLE_BACKEND_ENGINEER_THINKING="${LM_ROLE_BACKEND_ENGINEER_THINKING:-${LM_TIER_BUILD_THINKING}}"
LM_ROLE_FRONTEND_ENGINEER_MODEL="${LM_ROLE_FRONTEND_ENGINEER_MODEL:-${LM_TIER_BUILD_MODEL}}"
LM_ROLE_FRONTEND_ENGINEER_THINKING="${LM_ROLE_FRONTEND_ENGINEER_THINKING:-${LM_TIER_BUILD_THINKING}}"
LM_ROLE_DATA_ANALYST_MODEL="${LM_ROLE_DATA_ANALYST_MODEL:-${LM_TIER_ANALYSIS_MODEL}}"
LM_ROLE_DATA_ANALYST_THINKING="${LM_ROLE_DATA_ANALYST_THINKING:-${LM_TIER_ANALYSIS_THINKING}}"
LM_ROLE_ARCHITECT_MODEL="${LM_ROLE_ARCHITECT_MODEL:-${LM_TIER_BUILD_MODEL}}"
LM_ROLE_ARCHITECT_THINKING="${LM_ROLE_ARCHITECT_THINKING:-${LM_TIER_BUILD_THINKING}}"
LM_ROLE_TESTER_MODEL="${LM_ROLE_TESTER_MODEL:-${LM_TIER_VALIDATION_MODEL}}"
LM_ROLE_TESTER_THINKING="${LM_ROLE_TESTER_THINKING:-${LM_TIER_VALIDATION_THINKING}}"
LM_ROLE_QA_MODEL="${LM_ROLE_QA_MODEL:-${LM_TIER_VALIDATION_MODEL}}"
LM_ROLE_QA_THINKING="${LM_ROLE_QA_THINKING:-${LM_TIER_VALIDATION_THINKING}}"
LM_ROLE_INTEGRATOR_MODEL="${LM_ROLE_INTEGRATOR_MODEL:-${LM_TIER_ANALYSIS_MODEL}}"
LM_ROLE_INTEGRATOR_THINKING="${LM_ROLE_INTEGRATOR_THINKING:-${LM_TIER_ANALYSIS_THINKING}}"
LM_ROLE_INFRA_ENGINEER_MODEL="${LM_ROLE_INFRA_ENGINEER_MODEL:-${LM_TIER_BUILD_MODEL}}"
LM_ROLE_INFRA_ENGINEER_THINKING="${LM_ROLE_INFRA_ENGINEER_THINKING:-${LM_TIER_BUILD_THINKING}}"
LM_ROLE_CLAWSENTINEL_MODEL="${LM_ROLE_CLAWSENTINEL_MODEL:-${LM_TIER_BUILD_MODEL}}"
LM_ROLE_CLAWSENTINEL_THINKING="${LM_ROLE_CLAWSENTINEL_THINKING:-low}"
LM_ROLE_ANALYST_MODEL="${LM_ROLE_ANALYST_MODEL:-${LM_TIER_ANALYSIS_MODEL}}"
LM_ROLE_ANALYST_THINKING="${LM_ROLE_ANALYST_THINKING:-${LM_TIER_ANALYSIS_THINKING}}"

# =============================================================================
# SECTION 3 — FALLBACK CHAIN  (codex rate-limited → qwen → skip)
# =============================================================================
LM_FALLBACK_BIN="${LM_FALLBACK_BIN:-/home/venom/.npm-global/bin/qwen}"
LM_FALLBACK_MODEL="${LM_FALLBACK_MODEL:-qwen}"

# =============================================================================
# SECTION 4 — GLOBAL DEFAULTS  (lus par scripts qui ne connaissent pas les rôles)
# =============================================================================
LM_USED_MAIN_MODEL="${LM_USED_MAIN_MODEL:-${LM_TIER_ORCHESTRATION_MODEL}}"
LM_USED_MAIN_THINKING="${LM_USED_MAIN_THINKING:-${LM_TIER_ORCHESTRATION_THINKING}}"
LM_USED_ROLE_MODEL="${LM_USED_ROLE_MODEL:-${LM_TIER_BUILD_MODEL}}"
LM_USED_ROLE_THINKING="${LM_USED_ROLE_THINKING:-${LM_TIER_BUILD_THINKING}}"
LM_USED_ROLE_MIN_REFLECTION_PASSES="${LM_USED_ROLE_MIN_REFLECTION_PASSES:-2}"
LM_USED_QWEN_BIN="${LM_USED_QWEN_BIN:-${LM_FALLBACK_BIN}}"
LM_USED_QWEN_THINKING="${LM_USED_QWEN_THINKING:-}"
LM_USED_DIRECT_CRON_MODEL="${LM_USED_DIRECT_CRON_MODEL:-${LM_USED_ROLE_MODEL}}"
LM_USED_DIRECT_CRON_THINKING="${LM_USED_DIRECT_CRON_THINKING:-${LM_USED_ROLE_THINKING}}"
LM_USED_GATEWAY_MODEL="${LM_USED_GATEWAY_MODEL:-${LM_USED_ROLE_MODEL}}"
LM_USED_GATEWAY_THINKING="${LM_USED_GATEWAY_THINKING:-${LM_USED_ROLE_THINKING}}"
LM_USED_FALLBACK_MODEL="${LM_USED_FALLBACK_MODEL:-qwen}"
LM_USED_FALLBACK_THINKING="${LM_USED_FALLBACK_THINKING:-}"

# =============================================================================
# SECTION 5 — ALIASES backward-compat  (NE PAS MODIFIER — dérivés auto)
# =============================================================================
MODEL_CONFIG_MAIN_MODEL="${MODEL_CONFIG_MAIN_MODEL:-${LM_USED_MAIN_MODEL}}"
MODEL_CONFIG_MAIN_THINKING="${MODEL_CONFIG_MAIN_THINKING:-${LM_USED_MAIN_THINKING}}"
MODEL_CONFIG_PARALLEL_ROLE_MODEL="${MODEL_CONFIG_PARALLEL_ROLE_MODEL:-${LM_USED_ROLE_MODEL}}"
MODEL_CONFIG_PARALLEL_ROLE_THINKING="${MODEL_CONFIG_PARALLEL_ROLE_THINKING:-${LM_USED_ROLE_THINKING}}"
MODEL_CONFIG_PARALLEL_ROLE_MIN_REFLECTION_PASSES="${MODEL_CONFIG_PARALLEL_ROLE_MIN_REFLECTION_PASSES:-${LM_USED_ROLE_MIN_REFLECTION_PASSES}}"
MODEL_CONFIG_DIRECT_CRON_MODEL="${MODEL_CONFIG_DIRECT_CRON_MODEL:-${LM_USED_DIRECT_CRON_MODEL}}"
MODEL_CONFIG_DIRECT_CRON_THINKING="${MODEL_CONFIG_DIRECT_CRON_THINKING:-${LM_USED_DIRECT_CRON_THINKING}}"
MODEL_CONFIG_GATEWAY_MODEL="${MODEL_CONFIG_GATEWAY_MODEL:-${LM_USED_GATEWAY_MODEL}}"
MODEL_CONFIG_GATEWAY_THINKING="${MODEL_CONFIG_GATEWAY_THINKING:-${LM_USED_GATEWAY_THINKING}}"
MODEL_CONFIG_FALLBACK_MODEL="${MODEL_CONFIG_FALLBACK_MODEL:-${LM_USED_FALLBACK_MODEL}}"
MODEL_CONFIG_FALLBACK_THINKING="${MODEL_CONFIG_FALLBACK_THINKING:-${LM_USED_FALLBACK_THINKING}}"
MODEL_CONFIG_ROLE_MODEL="${MODEL_CONFIG_ROLE_MODEL:-${LM_USED_ROLE_MODEL}}"
MODEL_CONFIG_ROLE_THINKING="${MODEL_CONFIG_ROLE_THINKING:-${LM_USED_ROLE_THINKING}}"
