#!/usr/bin/env bash

# Compatibility shim.
# Canonical config now lives in lm_used_model_config.sh.
# Keep this file intentionally tiny: it only forwards to canonical config.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
LM_USED_MODEL_CONFIG_FILE="${SCRIPT_DIR}/lm_used_model_config.sh"

if [[ ! -f "$LM_USED_MODEL_CONFIG_FILE" ]]; then
  # If canonical config is missing, keep env-based backward compatibility only.
  MODEL_CONFIG_MAIN_MODEL="${MODEL_CONFIG_MAIN_MODEL:-}"
  MODEL_CONFIG_MAIN_THINKING="${MODEL_CONFIG_MAIN_THINKING:-}"
  MODEL_CONFIG_PARALLEL_ROLE_MODEL="${MODEL_CONFIG_PARALLEL_ROLE_MODEL:-}"
  MODEL_CONFIG_PARALLEL_ROLE_THINKING="${MODEL_CONFIG_PARALLEL_ROLE_THINKING:-}"
  MODEL_CONFIG_PARALLEL_ROLE_MIN_REFLECTION_PASSES="${MODEL_CONFIG_PARALLEL_ROLE_MIN_REFLECTION_PASSES:-}"
  MODEL_CONFIG_GATEWAY_MODEL="${MODEL_CONFIG_GATEWAY_MODEL:-${MODEL_CONFIG_PARALLEL_ROLE_MODEL:-}}"
  MODEL_CONFIG_GATEWAY_THINKING="${MODEL_CONFIG_GATEWAY_THINKING:-${MODEL_CONFIG_PARALLEL_ROLE_THINKING:-}}"
  MODEL_CONFIG_FALLBACK_MODEL="${MODEL_CONFIG_FALLBACK_MODEL:-${MODEL_CONFIG_PARALLEL_ROLE_MODEL:-}}"
  MODEL_CONFIG_FALLBACK_THINKING="${MODEL_CONFIG_FALLBACK_THINKING:-${MODEL_CONFIG_PARALLEL_ROLE_THINKING:-}}"
  MODEL_CONFIG_DIRECT_CRON_MODEL="${MODEL_CONFIG_DIRECT_CRON_MODEL:-${MODEL_CONFIG_PARALLEL_ROLE_MODEL:-}}"
  MODEL_CONFIG_DIRECT_CRON_THINKING="${MODEL_CONFIG_DIRECT_CRON_THINKING:-${MODEL_CONFIG_PARALLEL_ROLE_THINKING:-}}"
  MODEL_CONFIG_ROLE_MODEL="${MODEL_CONFIG_ROLE_MODEL:-${MODEL_CONFIG_PARALLEL_ROLE_MODEL:-}}"
  MODEL_CONFIG_ROLE_THINKING="${MODEL_CONFIG_ROLE_THINKING:-${MODEL_CONFIG_PARALLEL_ROLE_THINKING:-}}"
  if [[ -z "$MODEL_CONFIG_MAIN_MODEL" && -z "$MODEL_CONFIG_PARALLEL_ROLE_MODEL" ]]; then
    echo "WARN: lm_used_model_config.sh missing and no MODEL_CONFIG_* overrides set; model defaults undefined." >&2
  fi
else
  source "$LM_USED_MODEL_CONFIG_FILE"
fi
