#!/usr/bin/env python3
"""Bulk migration toward target backend architecture.

Moves legacy code from:
- backend/services -> backend/src/services
- backend/jobs -> backend/src/jobs
- backend/models -> backend/src/models

When a destination filename already exists, the source is moved to a dedicated
`legacy` namespace under the target layer.

After each move, a compatibility shim is written at the old path.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
import hashlib
import json
import shutil
from typing import Dict, List


ROOT = Path(__file__).resolve().parents[1]
TARGET_BACKEND = ROOT / "apps" / "api" / "src"
LEGACY_BACKEND = ROOT / "copilot-app" / "backend"
REPORT_PATH = ROOT / "docs" / "operations" / "ops" / "TARGET_ARCHITECTURE_LAYOUT.md"


@dataclass
class MoveRecord:
    area: str
    old_path: str
    new_path: str
    shim_import: str
    action: str


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def module_path_from_backend(path: Path) -> str:
    rel = path.relative_to(TARGET_BACKEND).with_suffix("")
    return ".".join(rel.parts)


def ensure_package_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    init_file = path / "__init__.py"
    if not init_file.exists():
        init_file.write_text(
            '"""Autogenerated package for target architecture migration."""\n',
            encoding="utf-8",
        )


def write_shim(old_path: Path, import_module: str, new_path: Path) -> None:
    old_path.write_text(
        "\n".join(
            [
                '"""Compatibility shim.',
                "",
                f"Module moved to `{new_path.relative_to(TARGET_BACKEND).as_posix()}`.",
                '"""',
                "",
                f"from {import_module} import *  # noqa: F401,F403",
                "",
            ]
        ),
        encoding="utf-8",
    )


def move_python_modules(
    *,
    area: str,
    source_dir: Path,
    target_dir: Path,
    duplicate_dir_name: str,
) -> List[MoveRecord]:
    records: List[MoveRecord] = []
    ensure_package_dir(target_dir)
    duplicate_dir = target_dir / duplicate_dir_name
    ensure_package_dir(duplicate_dir)

    for src_file in sorted(source_dir.glob("*.py")):
        if src_file.name == "__init__.py":
            continue

        primary_dst = target_dir / src_file.name
        dst = primary_dst
        action = "moved_primary"

        if primary_dst.exists():
            if sha256(primary_dst) == sha256(src_file):
                # same content; keep destination and only drop shim
                action = "shim_only_identical_already_in_target"
            else:
                dst = duplicate_dir / src_file.name
                action = "moved_duplicate_to_legacy"

        if action.startswith("moved"):
            dst.parent.mkdir(parents=True, exist_ok=True)
            if dst.exists():
                # avoid overwrite in repeated migrations
                stem = dst.stem
                suffix = dst.suffix
                idx = 1
                while True:
                    candidate = dst.parent / f"{stem}_migrated_{idx}{suffix}"
                    if not candidate.exists():
                        dst = candidate
                        break
                    idx += 1
            shutil.move(str(src_file), str(dst))
        else:
            dst = primary_dst

        import_module = module_path_from_backend(dst)
        write_shim(src_file, import_module, dst)

        records.append(
            MoveRecord(
                area=area,
                old_path=src_file.relative_to(ROOT).as_posix(),
                new_path=dst.relative_to(ROOT).as_posix(),
                shim_import=import_module,
                action=action,
            )
        )

    return records


def render_report(records: List[MoveRecord]) -> str:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    by_area: Dict[str, List[MoveRecord]] = {"services": [], "jobs": [], "models": []}
    for rec in records:
        by_area.setdefault(rec.area, []).append(rec)

    lines: List[str] = [
        "# Target Architecture Layout (Bulk Migration)",
        "",
        f"Generated at: `{generated_at}`",
        "",
        "This migration moved legacy runtime code into the target `src/*` architecture",
        "and left compatibility shims on old paths.",
        "",
        "## Target Architecture",
        "",
        "- `src/api/routes`: HTTP orchestrators only",
        "- `src/services`: application services",
        "- `src/analytics`, `src/core`, `src/research`: domain logic",
        "- `src/jobs`: batch/scheduler modules",
        "- `src/models`: model artifacts",
        "- `src/reuse`: stable import facades",
        "",
        "## Migration Summary",
        "",
        f"- Total migrated modules: `{len(records)}`",
        f"- Services: `{len(by_area.get('services', []))}`",
        f"- Jobs: `{len(by_area.get('jobs', []))}`",
        f"- Models: `{len(by_area.get('models', []))}`",
        "",
    ]

    for area in ("services", "jobs", "models"):
        area_records = by_area.get(area, [])
        lines.extend([f"## {area.capitalize()} Moves", ""])
        if not area_records:
            lines.append("- none")
            lines.append("")
            continue
        for rec in area_records:
            lines.append(
                "- "
                f"`{rec.old_path}` -> `{rec.new_path}` "
                f"(`{rec.action}`, shim: `{rec.shim_import}`)"
            )
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    ensure_package_dir(TARGET_BACKEND / "jobs")
    ensure_package_dir(TARGET_BACKEND / "services")
    ensure_package_dir(TARGET_BACKEND / "models")

    records: List[MoveRecord] = []
    records.extend(
        move_python_modules(
            area="services",
            source_dir=LEGACY_BACKEND / "services",
            target_dir=TARGET_BACKEND / "services",
            duplicate_dir_name="legacy",
        )
    )
    records.extend(
        move_python_modules(
            area="jobs",
            source_dir=LEGACY_BACKEND / "jobs",
            target_dir=TARGET_BACKEND / "jobs",
            duplicate_dir_name="legacy",
        )
    )
    records.extend(
        move_python_modules(
            area="models",
            source_dir=LEGACY_BACKEND / "models",
            target_dir=TARGET_BACKEND / "models",
            duplicate_dir_name="legacy",
        )
    )

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(render_report(records), encoding="utf-8")

    summary = {
        "migrated_modules": len(records),
        "report": REPORT_PATH.as_posix(),
        "services": len([r for r in records if r.area == "services"]),
        "jobs": len([r for r in records if r.area == "jobs"]),
        "models": len([r for r in records if r.area == "models"]),
    }
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
