name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          python -m playwright install chromium

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          make test

      - name: Start Streamlit (background)
        env:
          PYTHONPATH: ${{ github.workspace }}/src
          AF_UI_PORT: 5555
        run: |
          nohup bash -lc 'AF_UI_PORT=5555 bash scripts/ui_start.sh >/dev/null 2>&1 &' 
          for i in {1..20}; do curl -sf http://localhost:5555/_stcore/health && break || sleep 2; done

      - name: UI smoke (Playwright)
        env:
          PYTHONPATH: ${{ github.workspace }}/src
          UI_BASE: http://localhost:5555
        run: |
          python ops/ui/ui_smoke.py || true

      - name: Security audit
        run: |
          bash ops/security/security_scan.sh || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: |
            artifacts/**
            data/reports/**
