name: ci

on:
  push:
  pull_request:

jobs:
  api-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Setup venv + install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -U pip
          pip install -r requirements.txt
      - name: Generate API docs
        run: |
          . .venv/bin/activate
          python ops/docs/generate_api_docs.py
      - name: Check API docs up-to-date
        run: |
          if ! git diff --quiet -- docs/api; then
            echo 'API docs changed. Please run: make api-docs-generate and commit the updates.'
            git status --porcelain
            git --no-pager diff -- docs/api | head -n 200 || true
            exit 1
          fi

  ui-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Setup venv + install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -U pip
          pip install -r requirements.txt
      - name: Start Dash (background)
        run: |
          . .venv/bin/activate
          nohup python -m src.dash_app.app > dash.out 2>&1 &
          sleep 8
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: UI Health (Playwright)
        run: |
          npm i -D playwright
          npx playwright install chromium
          make ui-health || true
      - name: Smoke routes
        run: |
          . .venv/bin/activate
          make dash-smoke
      - name: Upload UI artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-health-artifacts
          path: |
            artifacts/ui_health
            data/reports
            dash.out
